### ISSUE TITLE
no connection to server with self signed certificate

### ISSUE THREAD

**Issue by hkoerschgen** [acomminos/Plumble#109]
Tried with tablet and smartphone. If the server has a self signed certificate, plumble go in an ui-deadlock with fail to add the certificate to the trust store.

**Comment by acomminos** [comment]
Can you attach a debugger during the hang and find out where it's freezing? That would be immensely helpful, thanks.

**Comment by hkoerschgen** [comment]
It's no real deadlock. After choosing allow on the modal view to the
untrusted certificate, the information "added certificate to trust store"
is displayed for 2 seconds. But after that the view "untrusted certificate"
is shown again.

If the debugger information can help, I do it. Do you have an url to a
small manual with the steps to do this?

**Comment by jeffre** [comment]
This is happening to me as well, if logs are still needed I'll be glad to provide.

**Comment by hjl3** [comment]
I've been encountering this issue with Plumble and my uMurmur server (self-signed and letsencrypt certs). Pulled the following from the system log when attempting to allow the certificate.
```
02-22 18:22:17.295: I/Jumble(10280): Using custom trust store /data/user/0/com.morlunk.mumbleclient.free/files/plumble-store.bks with system trust store
02-22 18:22:17.301: I/Jumble(10280): JumbleTCP: Connecting
02-22 18:22:17.488: V/Jumble(10280): Disconnected
02-22 18:22:17.502: W/System.err(10280): java.lang.IllegalArgumentException: Receiver not registered: com.morlunk.mumbleclient.service.ipc.TalkBroadcastReceiver@4fbaec1
02-22 18:22:17.503: W/System.err(10280): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:780)
02-22 18:22:17.503: W/System.err(10280): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1195)
02-22 18:22:17.503: W/System.err(10280): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
02-22 18:22:17.503: W/System.err(10280): 	at com.morlunk.mumbleclient.service.PlumbleService.onConnectionDisconnected(PlumbleService.java:315)
02-22 18:22:17.503: W/System.err(10280): 	at com.morlunk.jumble.net.JumbleConnection.onTLSHandshakeFailed(JumbleConnection.java:585)
02-22 18:22:17.503: W/System.err(10280): 	at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:101)
02-22 18:22:17.503: W/System.err(10280): 	at android.os.Handler.handleCallback(Handler.java:739)
02-22 18:22:17.503: W/System.err(10280): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 18:22:17.503: W/System.err(10280): 	at android.os.Looper.loop(Looper.java:148)
02-22 18:22:17.504: W/System.err(10280): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-22 18:22:17.504: W/System.err(10280): 	at java.lang.reflect.Method.invoke(Native Method)
02-22 18:22:17.504: W/System.err(10280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-22 18:22:17.504: W/System.err(10280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-22 18:22:18.404: I/Jumble(10280): Using custom trust store /data/user/0/com.morlunk.mumbleclient.free/files/plumble-store.bks with system trust store
02-22 18:22:18.406: I/Jumble(10280): JumbleTCP: Connecting
02-22 18:22:18.575: V/Jumble(10280): Disconnected
```

**Comment by jeremyvisser** [comment]
Can confirm this bug with a uMurmur server with a Let's Encrypt certificate.

I'm passing my fullchain.pem to the `certificate` parameter, and my privkey.pem to the `private_key` parameter.

The official Mumble client (1.2.16) connects to this server with no certificate warnings whatsoever (not even the self-signed warning -- it's trusted out of the box).

However when connecting with Plumble, I get an infinite loop of dialog boxes asking me to trust the certificate and can't get any further.

**Comment by jeremyvisser** [comment]
I finally got a chance to test using the official Mumble server instead of uMurmur.

Using the same hardware, same certificate, same Plumble version, but with the official Mumble server instead, it works fine.

Sounds like further diagnosis is required to figure out whether this is a problem with Plumble or uMurmur.

**Comment by ZeBaal** [comment]
I also have this problem occurring with plumble and umurmur. The problem is happening with openssl self-generated certificates and letsencrypt certificates too.
