### ISSUE TITLE
plumble crashes when I choose a server

### ISSUE THREAD

**Issue by kubimax** [acomminos/Plumble#136]
Hi,
I have been installed the 3.2.0 release of Plumble Free from Playstore. It's running correctly without problems in my phone Samsung SIII Neo (Android 4.4.2).

Next I uninstalled this app, downloaded the app sources and opened it with Android Studio 1.5.1. Once opened the sources I build all without errors. So I placed the APK file in my phone: the app start correctly but crashes when I choose a server I've setup (murmur server works correctly in my PC at 192.168.0.1:64738)
I can repeat the same crash also when I use the ADV emulator.
The question is: why the build release downloaded from Playstore works but sources compiled release crashes? The release mean be the same 3.2.0....
any suggest are welcome
Thanks
Max

**Comment by acomminos** [comment]
Please ensure Jumble's native libraries have been built successfully.

We should probably show a warning when Jumble fails to link in the future.

**Comment by kubimax** [comment]
Hi,
this is a part of log I can see at video when the app crashes in AVD:

02-08 11:49:15.227 6566-6566/com.morlunk.mumbleclient.free W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/morlunk/jumble/audio/javacpp/CELT7;
02-08 11:49:15.227 6566-6566/com.morlunk.mumbleclient.free D/AndroidRuntime: Shutting down VM
02-08 11:49:15.227 6566-6566/com.morlunk.mumbleclient.free W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb50e9180)
02-08 11:49:15.446 6566-6566/com.morlunk.mumbleclient.free E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.ExceptionInInitializerError
                                                                                 at com.morlunk.jumble.JumbleService.onConnectionEstablished(JumbleService.java:307)
                                                                                 at com.morlunk.jumble.net.JumbleConnection.onTCPConnectionEstablished(JumbleConnection.java:638)
                                                                                 at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:108)
                                                                                 at android.os.Handler.handleCallback(Handler.java:605)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4424)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.UnsatisfiedLinkError: Couldn't load jnicelt7: findLibrary returned null
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                 at java.lang.System.loadLibrary(System.java:535)
                                                                                 at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:711)
                                                                                 at com.googlecode.javacpp.Loader.load(Loader.java:586)
                                                                                 at com.googlecode.javacpp.Loader.load(Loader.java:540)
                                                                                 at com.morlunk.jumble.audio.javacpp.CELT7.<clinit>(CELT7.java:41)
                                                                                 at com.morlunk.jumble.JumbleService.onConnectionEstablished(JumbleService.java:307) 
                                                                                 at com.morlunk.jumble.net.JumbleConnection.onTCPConnectionEstablished(JumbleConnection.java:638) 
                                                                                 at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:108) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:605) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4424) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                                              Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gnustl_static: findLibrary returned null
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                 at java.lang.System.loadLibrary(System.java:535)
                                                                                 at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:711)
                                                                                 at com.googlecode.javacpp.Loader.load(Loader.java:577)
                                                                                 at com.googlecode.javacpp.Loader.load(Loader.java:540) 
                                                                                 at com.morlunk.jumble.audio.javacpp.CELT7.<clinit>(CELT7.java:41) 
                                                                                 at com.morlunk.jumble.JumbleService.onConnectionEstablished(JumbleService.java:307) 
                                                                                 at com.morlunk.jumble.net.JumbleConnection.onTCPConnectionEstablished(JumbleConnection.java:638) 
                                                                                 at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:108) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:605) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4424) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
02-08 11:49:16.026 6566-6569/com.morlunk.mumbleclient.free D/dalvikvm: GC_CONCURRENT freed 583K, 17% free 13216K/15815K, paused 7ms+187ms
02-08 11:49:16.237 6566-6570/com.morlunk.mumbleclient.free I/dalvikvm: threadid=3: reacting to signal 3
02-08 11:49:16.266 6566-6570/com.morlunk.mumbleclient.free I/dalvikvm: Wrote stack traces to '/data/anr/traces.txt'

**Comment by moonlies** [comment]
I can confirm this issue but with version 3.3.0-rc1 from f-droid on cyanogenmod.
Downgrading to 3.2.0 solved the problem for me.

**Comment by syedtehrimabbas** [comment]
I have same issue please resolve it.

**Comment by olzzon** [comment]
In #3.3.0-rc1 i have the same problem, and the only thing I know is that it´s related to Jumble - JavaCPP and IntPointer.

It happens after Plumble has connected to the server (I can see the PlumbleClient when logging in on another machine as SuperUser)  - 
When I look with debug can see that it´s when it calls:

Line 64:        IntPointer versionPtr = new IntPointer(); in public static int getBitstreamVersion() 
in CELT7.java
(Called from JumbleService.java line 334:  auth.addCeltVersions(CELT7.getBitstreamVersion());)

If I disable the call, the same happens problem occur later in 
Opus.Encoder.java line 56:  IntPointer error = new IntPointer(1);

Here´s the log:
06-30 11:43:22.374 10346-10346/com.morlunk.mumbleclient.free E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.morlunk.mumbleclient.free, PID: 10346
                                                                               java.lang.RuntimeException: No native JavaCPP library in memory. (Has Loader.load() been called?)
                                                                                   at com.googlecode.javacpp.IntPointer.<init>(IntPointer.java:78)
                                                                                   at com.googlecode.javacpp.IntPointer.<init>(IntPointer.java:49)
                                                                                   at com.morlunk.jumble.audio.javacpp.CELT7.getBitstreamVersion(CELT7.java:64)
                                                                                   at com.morlunk.jumble.JumbleService.onConnectionEstablished(JumbleService.java:334)
                                                                                   at com.morlunk.jumble.net.JumbleConnection.onTCPConnectionEstablished(JumbleConnection.java:638)
                                                                                   at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:108)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.googlecode.javacpp.IntPointer.allocateArray(int) (tried Java_com_googlecode_javacpp_IntPointer_allocateArray and Java_com_googlecode_javacpp_IntPointer_allocateArray__I)
                                                                                   at com.googlecode.javacpp.IntPointer.allocateArray(Native Method)
                                                                                   at com.googlecode.javacpp.IntPointer.<init>(IntPointer.java:76)
                                                                                   at com.googlecode.javacpp.IntPointer.<init>(IntPointer.java:49) 
                                                                                   at com.morlunk.jumble.audio.javacpp.CELT7.getBitstreamVersion(CELT7.java:64) 
                                                                                   at com.morlunk.jumble.JumbleService.onConnectionEstablished(JumbleService.java:334) 
                                                                                   at com.morlunk.jumble.net.JumbleConnection.onTCPConnectionEstablished(JumbleConnection.java:638) 
                                                                                   at com.morlunk.jumble.net.JumbleTCP$1.run(JumbleTCP.java:108) 
                                                                                   at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
06-30 11:43:23.902 10346-10346/? I/Process: Sending signal. PID: 10346 SIG: 9

**Comment by shakib1377** [comment]
does anybody figured out how to solve this problem?
